version: '3'

services:
  localstack:
    # https://github.com/localstack/localstack/issues/5160
    image: localstack/localstack:0.13.0
    environment:
      # see document https://docs.localstack.cloud/localstack/configuration/
      - SERVICES=sqs,lambda
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      # about LAMBDA_EXECUTOR, I think...
      #   stability: docker > docker-reuse > local
      #   speed:     docker < docker-reuse < local
      # if you use docker-reuse mode, you have to stop lambda executing container(lambci/lambda:java11) manually.
      # if you use docker mode and sqs, many zombie lambda executing containers are created(!?)
      - LAMBDA_EXECUTOR=local
      # lambda log is output only when debug mode (perhaps...)
      # error log is output even if not in debug mode, but success log is not so.
      - DEBUG=1
      # I was hoping the following statement would work
      # - LS_LOG=info
    volumes:
      - ./localstack:/tmp/localstack
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - 4566:4566